apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-db-deployment-aks
  labels:
    app: song-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-db
  template:
    metadata:
      labels:
        app: song-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: music-config-aks
              key: SONG_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: music-secrets-aks
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: music-secrets-aks
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: song-db-service-aks
  labels:
    app: song-db
spec:
  selector:
    app: song-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP