apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service-aks
  labels:
    app: song-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
      - name: song-service-container
        image: mimusicacr.azurecr.io/song-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_HOST
          value: song-db-service-aks
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: music-config-aks
              key: SONG_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: music-secrets-aks
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: music-secrets-aks
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: song-service-aks
  labels:
    app: song-service
spec:
  selector:
    app: song-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer